[package]
name = "rush-crush"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.15.1", features = ["wayland"]}
bevy_rapier2d = "0.28.0"
bevy_ecs_ldtk = "0.11.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
